# HEADER FIELD BYTE LOCATION #
VERSION_LOCATION = 0
PROTOCOL_LOCATION = 0
FLAGS_LOCATION = 1
PADDING_LOCATION = 1
LENGTH_LOCATION = 2

# HEADER FIELD SIZE (BYTES) #
LENGTH_SIZE = 2

# HEADER SIZE (BITS)
HEADER_SIZE = 32
BYTE_SIZE = 8

# VERSION #
DEFAULT_VERSION = 1

# PROTOCOLS #
SP_PROTOCOL = 0
IDP_PROTOCOL = 1
DVCP_PROTOCOL = 2
DGP_PROTOCOL = 3

# FLAGS #
SP_REQUEST_FLAG = 0
SP_RESPONSE_FLAG = 1
IDP_REQUEST_FLAG = 0
IDP_RESPONSE_FLAG = 1
DVCP_DET_FLAG = 0
DVCP_ACK_FLAG = 1
DGP_REG_FLAG = 0
DGP_DEV_FLAG = 1

# ENCODING STANDARDS (BYTES) #
IP_ADDRESS_SIZE = 4
TCP_UDP_PORT_SIZE = 2
IP_PROTOCOL_SIZE = 1
SAMPLE_SIZE = 312
UUID_SIZE = 32

# JAVA SPECIFIC ENCODING (BYTES) #
FLOAT_SIZE = 4
CHAR_SIZE = 2

# SAMPLES #
SAMPLE_NUMBER_OF_FLOAT_VALUES = 76
SAMPLE_TOTAL_NUMBER_OF_VALUES = 81

# DETECTORS #
DETECTOR_NUMBER_OF_FLOAT_VALUES = 156

# CONNECTED APPLIANCE VARIABLES #
CONNECTED_APPLIANCE_STATUS_CHECK_INTERVAL = 1000 * 60 * 30

# DEFAULT_IP_ADDRESS
IP_ADDRESS_SYS_ADMIN = '192.168.1.50'
IP_ADDRESS_VALIDATOR = '192.168.1.49'
LOCALHOST = 'localhost'

# DEEP NEURAL NETWORK
RETRAINING_INTERVAL = 60 * 30
